"""initial normalized schema

Revision ID: dafb9b3b44eb
Revises: 
Create Date: 2026-06-07 09:05:43.172749
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dafb9b3b44eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('schemes',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schemes')),
    sa.UniqueConstraint('code', name=op.f('uq_schemes_code'))
    )
    op.create_index('ix_schemes_active_category', 'schemes', ['is_active', 'category'], unique=False)
    op.create_index('ix_schemes_active_state', 'schemes', ['is_active', 'state'], unique=False)
    op.create_index(op.f('ix_schemes_category'), 'schemes', ['category'], unique=False)
    op.create_index(op.f('ix_schemes_state'), 'schemes', ['state'], unique=False)
    op.create_table('eligibility_rules',
    sa.Column('scheme_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], name=op.f('fk_eligibility_rules_scheme_id_schemes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eligibility_rules')),
    sa.UniqueConstraint('scheme_id', 'code', name='uq_eligibility_rules_code')
    )
    op.create_index('ix_rules_scheme_active_priority', 'eligibility_rules', ['scheme_id', 'is_active', 'priority'], unique=False)
    op.create_table('required_documents',
    sa.Column('scheme_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata_schema', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], name=op.f('fk_required_documents_scheme_id_schemes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_required_documents')),
    sa.UniqueConstraint('scheme_id', 'code', name='uq_required_documents_code')
    )
    op.create_index('ix_required_documents_scheme', 'required_documents', ['scheme_id', 'is_active'], unique=False)
    op.create_table('scheme_versions',
    sa.Column('scheme_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('authority', sa.String(length=200), nullable=False),
    sa.Column('benefit_summary', sa.Text(), nullable=True),
    sa.Column('application_url', sa.String(length=1000), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], name=op.f('fk_scheme_versions_scheme_id_schemes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheme_versions')),
    sa.UniqueConstraint('scheme_id', 'version_number', name='uq_scheme_versions_number')
    )
    op.create_index('ix_scheme_versions_published', 'scheme_versions', ['scheme_id', 'is_published'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('supabase_user_id', sa.Uuid(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_supabase_user_id'), 'users', ['supabase_user_id'], unique=True)
    op.create_table('action_plans',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('scheme_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], name=op.f('fk_action_plans_scheme_id_schemes')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_action_plans_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_plans'))
    )
    op.create_index('ix_action_plans_user_status', 'action_plans', ['user_id', 'status'], unique=False)
    op.create_table('admins',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('department', sa.String(length=160), nullable=True),
    sa.Column('designation', sa.String(length=160), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_admins_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admins')),
    sa.UniqueConstraint('user_id', name=op.f('uq_admins_user_id'))
    )
    op.create_table('agriculture_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('land_area_acres', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('land_ownership', sa.String(length=80), nullable=True),
    sa.Column('crop_type', sa.String(length=120), nullable=True),
    sa.Column('pm_kisan_status', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_agriculture_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agriculture_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_agriculture_profiles_user_id'))
    )
    op.create_index(op.f('ix_agriculture_profiles_crop_type'), 'agriculture_profiles', ['crop_type'], unique=False)
    op.create_table('ai_usage_logs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('request_id', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_usage_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_usage_logs'))
    )
    op.create_index(op.f('ix_ai_usage_logs_request_id'), 'ai_usage_logs', ['request_id'], unique=False)
    op.create_index('ix_ai_usage_user_created', 'ai_usage_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('trace_id', sa.String(length=80), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_actor_created', 'audit_logs', ['actor_user_id', 'created_at'], unique=False)
    op.create_index('ix_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_trace_id'), 'audit_logs', ['trace_id'], unique=False)
    op.create_table('education_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('course', sa.String(length=180), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('marks', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_student', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_education_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_education_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_education_profiles_user_id'))
    )
    op.create_index(op.f('ix_education_profiles_course'), 'education_profiles', ['course'], unique=False)
    op.create_table('eligibility_decisions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('scheme_id', sa.Uuid(), nullable=False),
    sa.Column('scheme_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('profile_snapshot', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=False),
    sa.Column('ruleset_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], name=op.f('fk_eligibility_decisions_scheme_id_schemes')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_eligibility_decisions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eligibility_decisions'))
    )
    op.create_index('ix_eligibility_user_scheme_created', 'eligibility_decisions', ['user_id', 'scheme_id', 'created_at'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('template_code', sa.String(length=120), nullable=False),
    sa.Column('recipient', sa.String(length=320), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_user_status', 'notifications', ['user_id', 'status', 'created_at'], unique=False)
    op.create_table('profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('annual_income', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_profiles_user_id'))
    )
    op.create_index(op.f('ix_profiles_annual_income'), 'profiles', ['annual_income'], unique=False)
    op.create_index(op.f('ix_profiles_category'), 'profiles', ['category'], unique=False)
    op.create_index(op.f('ix_profiles_district'), 'profiles', ['district'], unique=False)
    op.create_index(op.f('ix_profiles_state'), 'profiles', ['state'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.Uuid(), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['refresh_tokens.id'], name=op.f('fk_refresh_tokens_replaced_by_id_refresh_tokens')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name='uq_refresh_tokens_token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index('ix_refresh_tokens_user_active', 'refresh_tokens', ['user_id', 'revoked_at', 'expires_at'], unique=False)
    op.create_table('rule_versions',
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('expression', sa.JSON(), nullable=False),
    sa.Column('explanation_pass', sa.String(length=500), nullable=False),
    sa.Column('explanation_fail', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['eligibility_rules.id'], name=op.f('fk_rule_versions_rule_id_eligibility_rules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_versions')),
    sa.UniqueConstraint('rule_id', 'version_number', name='uq_rule_versions_number')
    )
    op.create_index('ix_rule_versions_active', 'rule_versions', ['rule_id', 'is_active'], unique=False)
    op.create_table('user_documents',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('document_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('storage_key', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('issued_at', sa.Date(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_documents_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_documents'))
    )
    op.create_index('ix_user_documents_user_code_status', 'user_documents', ['user_id', 'document_code', 'status'], unique=False)
    op.create_table('women_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('marital_status', sa.String(length=40), nullable=True),
    sa.Column('children_count', sa.Integer(), nullable=True),
    sa.Column('pregnancy_status', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_women_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_women_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_women_profiles_user_id'))
    )
    op.create_table('recommendations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('scheme_id', sa.Uuid(), nullable=False),
    sa.Column('eligibility_decision_id', sa.Uuid(), nullable=False),
    sa.Column('match_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('priority_score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['eligibility_decision_id'], ['eligibility_decisions.id'], name=op.f('fk_recommendations_eligibility_decision_id_eligibility_decisions')),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], name=op.f('fk_recommendations_scheme_id_schemes')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recommendations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations')),
    sa.UniqueConstraint('user_id', 'scheme_id', name='uq_recommendations_user_scheme')
    )
    op.create_index('ix_recommendations_user_rank', 'recommendations', ['user_id', 'priority_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recommendations_user_rank', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_table('women_profiles')
    op.drop_index('ix_user_documents_user_code_status', table_name='user_documents')
    op.drop_table('user_documents')
    op.drop_index('ix_rule_versions_active', table_name='rule_versions')
    op.drop_table('rule_versions')
    op.drop_index('ix_refresh_tokens_user_active', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_profiles_state'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_district'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_category'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_annual_income'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index('ix_notifications_user_status', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_eligibility_user_scheme_created', table_name='eligibility_decisions')
    op.drop_table('eligibility_decisions')
    op.drop_index(op.f('ix_education_profiles_course'), table_name='education_profiles')
    op.drop_table('education_profiles')
    op.drop_index(op.f('ix_audit_logs_trace_id'), table_name='audit_logs')
    op.drop_index('ix_audit_entity', table_name='audit_logs')
    op.drop_index('ix_audit_actor_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_ai_usage_user_created', table_name='ai_usage_logs')
    op.drop_index(op.f('ix_ai_usage_logs_request_id'), table_name='ai_usage_logs')
    op.drop_table('ai_usage_logs')
    op.drop_index(op.f('ix_agriculture_profiles_crop_type'), table_name='agriculture_profiles')
    op.drop_table('agriculture_profiles')
    op.drop_table('admins')
    op.drop_index('ix_action_plans_user_status', table_name='action_plans')
    op.drop_table('action_plans')
    op.drop_index(op.f('ix_users_supabase_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_scheme_versions_published', table_name='scheme_versions')
    op.drop_table('scheme_versions')
    op.drop_index('ix_required_documents_scheme', table_name='required_documents')
    op.drop_table('required_documents')
    op.drop_index('ix_rules_scheme_active_priority', table_name='eligibility_rules')
    op.drop_table('eligibility_rules')
    op.drop_index(op.f('ix_schemes_state'), table_name='schemes')
    op.drop_index(op.f('ix_schemes_category'), table_name='schemes')
    op.drop_index('ix_schemes_active_state', table_name='schemes')
    op.drop_index('ix_schemes_active_category', table_name='schemes')
    op.drop_table('schemes')
    op.drop_table('roles')
    # ### end Alembic commands ###

