"""create scheme tables

Revision ID: 73b3d9c4c7a1
Revises: dde0e9c71e46
Create Date: 2026-06-14 09:23:35.799346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73b3d9c4c7a1'
down_revision: Union[str, Sequence[str], None] = 'dde0e9c71e46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
