"""create scheme documents table
Revision ID: 8c523d0bc12b
Revises: 3af5bb339539
Create Date: 2026-06-14 20:31:28.277115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c523d0bc12b'
down_revision: Union[str, Sequence[str], None] = '3af5bb339539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheme_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheme_documents')
    # ### end Alembic commands ###
