"""create sector and scheme tables

Revision ID: f7f15bdd2aa6
Revises: 161b90fa33a1
Create Date: 2026-06-14 09:35:47.094177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7f15bdd2aa6'
down_revision: Union[str, Sequence[str], None] = '161b90fa33a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schemes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_name', sa.String(length=255), nullable=False),
    sa.Column('scheme_code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('official_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_code'),
    sa.UniqueConstraint('scheme_name')
    )
    op.create_table('agriculture_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('land_area_acres', sa.Float(), nullable=True),
    sa.Column('land_ownership', sa.String(length=50), nullable=True),
    sa.Column('crop_type', sa.String(length=100), nullable=True),
    sa.Column('pm_kisan_status', sa.Boolean(), nullable=False),
    sa.Column('irrigation_available', sa.Boolean(), nullable=False),
    sa.Column('farmer_category', sa.String(length=50), nullable=True),
    sa.Column('livestock_owned', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agriculture_profiles_user_id'), 'agriculture_profiles', ['user_id'], unique=True)
    op.create_table('education_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('education_level', sa.String(length=50), nullable=True),
    sa.Column('institution_name', sa.String(length=255), nullable=True),
    sa.Column('course', sa.String(length=100), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=True),
    sa.Column('academic_year', sa.Integer(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('board', sa.String(length=100), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('cgpa', sa.Float(), nullable=True),
    sa.Column('current_status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_profiles_user_id'), 'education_profiles', ['user_id'], unique=True)
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('annual_income', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_student', sa.Boolean(), nullable=False),
    sa.Column('is_woman', sa.Boolean(), nullable=False),
    sa.Column('is_farmer', sa.Boolean(), nullable=False),
    sa.Column('is_senior_citizen', sa.Boolean(), nullable=False),
    sa.Column('is_disabled', sa.Boolean(), nullable=False),
    sa.Column('is_worker', sa.Boolean(), nullable=False),
    sa.Column('profile_completion_percentage', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    op.create_table('scheme_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheme_versions_scheme_id'), 'scheme_versions', ['scheme_id'], unique=False)
    op.create_table('women_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('marital_status', sa.String(length=50), nullable=True),
    sa.Column('children_count', sa.Integer(), nullable=True),
    sa.Column('pregnancy_status', sa.Boolean(), nullable=False),
    sa.Column('widow_status', sa.Boolean(), nullable=False),
    sa.Column('single_mother_status', sa.Boolean(), nullable=False),
    sa.Column('self_help_group_member', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_women_profiles_user_id'), 'women_profiles', ['user_id'], unique=True)
    op.create_table('eligibility_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_version_id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('logical_operator', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['scheme_version_id'], ['scheme_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eligibility_rules_scheme_version_id'), 'eligibility_rules', ['scheme_version_id'], unique=False)
    op.create_table('rule_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eligibility_rule_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('comparison_operator', sa.String(length=20), nullable=False),
    sa.Column('comparison_value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['eligibility_rule_id'], ['eligibility_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_conditions_eligibility_rule_id'), 'rule_conditions', ['eligibility_rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rule_conditions_eligibility_rule_id'), table_name='rule_conditions')
    op.drop_table('rule_conditions')
    op.drop_index(op.f('ix_eligibility_rules_scheme_version_id'), table_name='eligibility_rules')
    op.drop_table('eligibility_rules')
    op.drop_index(op.f('ix_women_profiles_user_id'), table_name='women_profiles')
    op.drop_table('women_profiles')
    op.drop_index(op.f('ix_scheme_versions_scheme_id'), table_name='scheme_versions')
    op.drop_table('scheme_versions')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_education_profiles_user_id'), table_name='education_profiles')
    op.drop_table('education_profiles')
    op.drop_index(op.f('ix_agriculture_profiles_user_id'), table_name='agriculture_profiles')
    op.drop_table('agriculture_profiles')
    op.drop_table('schemes')
    # ### end Alembic commands ###
