"""add scheme documents and human readable conditions

Revision ID: f900409f5523
Revises: f7f15bdd2aa6
Create Date: 2026-06-14 11:11:46.245948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f900409f5523'
down_revision: Union[str, Sequence[str], None] = 'f7f15bdd2aa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rule_conditions', sa.Column('human_readable_condition', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rule_conditions', 'human_readable_condition')
    # ### end Alembic commands ###
